In [21]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns


In [22]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\AppData\Local\Packages\5319275A.51895FA4EA97F_cv1g1gvanyjgm\LocalState\sessions\01A1B9BDB8A069AEFD8D2D9C9DFA298DF7304A02\transfers\2025-27\Old_Bikes_encoded.csv")
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      0
1     119900.0     11000.0      1  4.0  350.0      1
2     600000.0       110.0      1  8.0  675.0      2
3      65000.0     16329.0      1  4.0  180.0      0
4      80000.0     10000.0      1  3.0  150.0      3
...        ...         ...    ...  ...    ...    ...
7319   25000.0     48587.0      1  8.0  150.0      5
7320   35000.0     60000.0      1  9.0  220.0      6
7321  450000.0      3430.0      1  4.0  750.0     14
7322  139000.0     21300.0      1  4.0  400.0      6
7323   80000.0      7127.0      1  5.0  220.0      6

[7324 rows x 6 columns]

In [23]:
# Make sure to define or load 'df' before using it.
# Example: Load a DataFrame from a CSV file
# df = pd.read_csv('your_data.csv')

x = df.drop('price', axis=1) # type: ignore
y = df[['price']]
y


price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7319   25000.0
7320   35000.0
7321  450000.0
7322  139000.0
7323   80000.0

[7324 rows x 1 columns]

In [24]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test =train_test_split(x, y, random_state= 42, test_size=0.2)
x_train

kms_driven  owner   age  power  brand
4506     68857.0      1  15.0  110.0      0
2758      5740.0      1   6.0  500.0      1
640      28329.0      1   6.0  110.0      5
5824     42966.0      1   7.0  150.0      3
6703      8000.0      1   5.0  500.0      1
...          ...    ...   ...    ...    ...
5191     56000.0      1   9.0  200.0      6
5226     22493.0      1   5.0  500.0      1
5390     17477.0      1   5.0  150.0      6
860      14836.0      1   8.0  150.0      3
7270      8000.0      1  10.0  250.0      4

[5859 rows x 5 columns]

In [25]:
x_test

kms_driven  owner   age  power  brand
3795     22500.0      1   6.0  350.0      1
1562      3198.0      1   5.0  500.0      1
4480     15000.0      1   6.0  220.0      6
3718     27000.0      1  12.0  150.0      3
5887     16764.0      1   9.0  100.0      5
...          ...    ...   ...    ...    ...
4417     16523.0      1   5.0  750.0     14
527       2881.0      1   7.0  250.0     13
3309     23833.0      1   4.0  150.0      7
5077      9282.0      1   7.0  500.0      1
565       2980.0      1   6.0  160.0      0

[1465 rows x 5 columns]

In [26]:
y_test

price
3795   88400.0
1562  102850.0
4480   67000.0
3718   30000.0
5887   20000.0
...        ...
4417  395000.0
527   140000.0
3309   54500.0
5077  114000.0
565    36000.0

[1465 rows x 1 columns]

In [27]:
y_train

price
4506   18000.0
2758  140000.0
640    32000.0
5824   40000.0
6703  160000.0
...        ...
5191   48928.0
5226  114000.0
5390   41000.0
860    40000.0
7270   80000.0

[5859 rows x 1 columns]

In [28]:
y_train.shape, x_train.shape , x_test.shape, y_test.shape

((5859, 1), (5859, 5), (1465, 5), (1465, 1))

In [29]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression
# Instantiate the LinearRegression model
lr = LinearRegression()
lr

LinearRegression()

In [30]:
x_train.shape


(5859, 5)

In [31]:
y_train.shape 

(5859, 1)

In [32]:
# Score the already instantiated LinearRegression model on the training set
lr.fit(x_train, y_train)
lr.score(x_train, y_train)

0.7053826605671762

In [33]:
# Fit the model if not already fitted
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.7586900869386206

In [34]:
# Predict prices for the training set
lr.predict(x_train)

array([[-56720.62686909],
       [212683.20959755],
       [ 23791.81811851],
       ...,
       [ 60210.48494031],
       [ 22702.41744365],
       [ 82553.52111097]], shape=(5859, 1))

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\AppData\Local\Packages\5319275A.51895FA4EA97F_cv1g1gvanyjgm\LocalState\sessions\01A1B9BDB8A069AEFD8D2D9C9DFA298DF7304A02\transfers\2025-27\laptopPrice.csv")
df

brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0      ASUS           Intel        Core i3            10th   4 GB     DDR4   
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4   
3      ASUS           Intel        Core i5            10th   8 GB     DDR4   
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4   
..      ...             ...            ...             ...    ...      ...   
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4   
822  Lenovo             AMD        Ryzen 5            10th   8 GB     DDR4   

         ssd      hdd       os  os_bit graphic_card_gb      weight  \
0       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
1       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
2       0 GB  1024 GB  Windows  64-bit            0 GB      Casual   
3     512 GB     0 GB  Windows  32-bit            2 GB      Casual   
4       0 GB   512 GB  Windows  64-bit            0 GB      Casual   
..       ...      ...      ...     ...             ...         ...   
818  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
819  1024 GB     0 GB  Windows  64-bit            0 GB      Casual   
820  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
821  1024 GB     0 GB  Windows  64-bit            4 GB      Casual   
822   512 GB     0 GB      DOS  64-bit            0 GB  ThinNlight   

        warranty Touchscreen msoffice   Price   rating  Number of Ratings  \
0    No warranty          No       No   34649  2 stars                  3   
1    No warranty          No       No   38999  3 stars                 65   
2    No warranty          No       No   39999  3 stars                  8   
3    No warranty          No       No   69990  3 stars                  0   
4    No warranty          No       No   26990  3 stars                  0   
..           ...         ...      ...     ...      ...                ...   
818       1 year          No       No  135990  3 stars                  0   
819       1 year          No       No  144990  3 stars                  0   
820       1 year          No       No  149990  3 stars                  0   
821       1 year          No       No  142990  3 stars                  0   
822  No warranty          No       No   57490  4 stars                 18   

     Number of Reviews  
0                    0  
1                    5  
2                    1  
3                    0  
4                    0  
..                 ...  
818                  0  
819                  0  
820                  0  
821                  0  
822                  4  

[823 rows x 19 columns]

In [7]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression
# Instantiate the LinearRegression model
lr = LinearRegression()
lr

LinearRegression()

In [9]:
from sklearn.model_selection import train_test_split

# Prepare features and target
x = df.drop('Price', axis=1)
y = df[['Price']]

# Split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.2)

x_train.shape


(658, 18)

In [11]:
x_train


brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
239    ASUS           Intel        Core i5            11th  16 GB     DDR4   
707    acer             AMD        Ryzen 5   Not Available   4 GB     DDR4   
759    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4   
432    ASUS           Intel        Core i5            10th   8 GB     DDR4   
299    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X   
..      ...             ...            ...             ...    ...      ...   
71   Lenovo           Intel        Core i3            11th   4 GB     DDR4   
106      HP           Intel        Core i3            11th   8 GB     DDR4   
270  Lenovo           Intel        Core i5            11th   8 GB     DDR4   
435     MSI           Intel        Core i5            10th   8 GB   LPDDR4   
102    ASUS           Intel        Core i3            11th   8 GB     DDR4   

        ssd      hdd       os  os_bit graphic_card_gb      weight  \
239  512 GB     0 GB  Windows  64-bit            0 GB      Casual   
707  512 GB     0 GB  Windows  64-bit            0 GB      Casual   
759  512 GB     0 GB  Windows  32-bit            4 GB      Casual   
432    0 GB  1024 GB  Windows  64-bit            2 GB      Casual   
299  512 GB     0 GB  Windows  32-bit            0 GB      Casual   
..      ...      ...      ...     ...             ...         ...   
71   256 GB     0 GB  Windows  64-bit            0 GB      Casual   
106  512 GB     0 GB  Windows  64-bit            0 GB  ThinNlight   
270  512 GB     0 GB  Windows  64-bit            0 GB      Casual   
435    0 GB   512 GB      DOS  32-bit            8 GB      Casual   
102  512 GB     0 GB  Windows  64-bit            0 GB  ThinNlight   

        warranty Touchscreen msoffice   rating  Number of Ratings  \
239       1 year          No       No  3 stars                  0   
707       1 year          No       No  4 stars                313   
759  No warranty          No       No  3 stars                  0   
432  No warranty          No       No  3 stars                  0   
299       1 year          No      Yes  4 stars                 76   
..           ...         ...      ...      ...                ...   
71   No warranty          No       No  4 stars                 10   
106  No warranty          No       No  3 stars                  0   
270      3 years         Yes      Yes  4 stars                 48   
435  No warranty          No       No  4 stars                 24   
102       1 year          No      Yes  3 stars                  0   

     Number of Reviews  
239                  0  
707                 39  
759                  0  
432                  0  
299                 14  
..                 ...  
71                   1  
106                  0  
270                 12  
435                  5  
102                  0  

[658 rows x 18 columns]

In [13]:
# One-hot encode categorical variables
x_train_encoded = pd.get_dummies(x_train)
y_train_array = y_train.values.ravel()  # Flatten y_train to 1D array

svg = SVR()
svg.fit(x_train_encoded, y_train_array)

SVR()

In [22]:
svg.fit(x_train, y_train)

SVR()

In [21]:
svg.score(x_train_encoded, y_train_array)

-0.06482137007973421

In [19]:
# Convert x_test to DataFrame with the same columns as x_train before encoding
x_test_df = pd.DataFrame(x_test, columns=x_train_encoded.columns[:x_test.shape[1]])

# One-hot encode x_test_df to match x_train_encoded columns
x_test_encoded = pd.get_dummies(x_test_df)
x_test_encoded = x_test_encoded.reindex(columns=x_train_encoded.columns, fill_value=0)

# Flatten y_test if needed
y_test_array = y_test.ravel() if hasattr(y_test, 'ravel') else y_test

svg.score(x_test_encoded, y_test_array)

-6043233349.049032

In [14]:
from sklearn.svm import SVC
svc_obj = SVC()
from sklearn.datasets import load_iris
x, y = load_iris(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train , x_test, y_train , y_test = train_test_split(x, y , random_state=42 , test_size=0.2)
svc_obj.fit(x_train , y_train)
svc_obj.score(x_train, y_train)
svc_obj.score(x_test, y_test)

1.0

In [15]:
svc_obj.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [16]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [25]:
##knn
from sklearn.neighbors import KNeighborsClassifier
knn_obj = KNeighborsClassifier()
knn_obj.fit(x_train, y_train)
knn_obj.score(x_train, y_train)
knn_obj.score(x_test, y_test)

1.0

In [26]:
knn_obj.score(x_train, y_train)

0.9666666666666667

In [27]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()

In [28]:
knn.fit(x_train, y_train)

KNeighborsRegressor()

In [29]:
knn_obj.score(x_train, y_train)

0.9666666666666667

In [30]:
knn_obj.score(x_test, y_test)

1.0