In [1]:
import numpy as np   ### numpy as np and import keywords

In [2]:
np.__version__

'2.3.1'

In [5]:
#array and list
### list convert into array
lst = [1, 2, 3, 4, 5]
print("list:", lst)
print(type(lst))

arr = np.array(lst)
print("array:", arr)
print("type of array:", type(arr)) 

list: [1, 2, 3, 4, 5]
<class 'list'>
array: [1 2 3 4 5]
type of array: <class 'numpy.ndarray'>


In [8]:
lst = list(range(0, 21))

In [9]:
arr = np.array(lst)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [12]:
arr =np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
arr = np.arange(1, 20)
type(arr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [15]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [16]:
arr=np.zeros((5, 10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((5, 10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.linspace(1, 10, 5)  # start, stop, number of elements

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
#1d array convert into 2d array

arr = np.array([1, 2, 3, 4, 5])
arr
arr_2d = arr.reshape(1, 5)  # Reshape to 1 row and 5 columns
arr_2d



array([[1, 2, 3, 4, 5]])

In [35]:
arr_5x6 = arr.flatten()[:30].reshape(5, 6)  # Take first 30 elements and reshape
arr_5x6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
arr = arr.reshape(10, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [27]:
arr = np.random.random((5, 10))
arr.ndim

2

In [28]:
arr = np.arange(60).reshape(12,5)
print("shape of array:", arr.shape)
print("size of array:", arr.size)
print("dimension of array:", arr.ndim)
print("data type of array:", arr.dtype)

shape of array: (12, 5)
size of array: 60
dimension of array: 2
data type of array: int64


In [29]:
arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [36]:
#2d array convert into 1d array

arr = np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [37]:
arr.flatten()  # Convert to 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [38]:
arr.ravel()  # Convert to 1D array, similar to flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
arr.shape
arr.T.shape

(5, 12)

In [42]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[0]= 100
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [44]:
arr = np.arange(60).reshape(3, 4, 5)  # 3D array with shape (3, 4, 5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [53]:
# The variable 'arr' is currently a scalar (np.int64), not an array.
# To access the element at row 5, column 4, use 'arr_5x6' which is a 2D array.
# arr_5x6 has shape (5, 6), so valid row indices are 0 to 4.
arr_5x6[4, 4]  # Access the last row (index 4), column 4

np.int64(28)

In [56]:
arr_5x6[0:5, 1:2]  # Accessing a sub-array from the 2D array arr_5x6

array([[ 1],
       [ 7],
       [13],
       [19],
       [25]])

In [59]:
arr_5x6[4, 4] = 100  # Assign 100 to row 4, column 4 of arr_5x6
arr_5x6

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27, 100,  29]])

### 3D Array

In [65]:
arr = np.arange(225).reshape(5, 15, 3)  # Create a 5x15x3 array with values from 0 to 224
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [67]:
arr[:, 0,:]   # : table , 0 row , : column

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [69]:
arr[:, 0:1 , 0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [72]:
arr[2][3][1]= 100
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [73]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [74]:
arr+2
arr*2
arr-2       
arr/2
arr+arr
arr*arr 
arr- arr


array([0, 0, 0, 0, 0])

In [76]:
arr[2:]  # This will return elements from index 2 to the end: array([3, 4, 5])

array([3, 4, 5])

In [78]:
# adding two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 + arr2  # Element-wise addition

array([5, 7, 9])

In [79]:
arr1 * arr2 

array([ 4, 10, 18])

In [80]:
arr1 - arr2  # Element-wise subtraction


array([-3, -3, -3])

In [81]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [82]:
arr1+arr1

array([2, 4, 6])

In [85]:
arr2 + arr2

array([ 8, 10, 12])

In [86]:
arr1 ** arr1  # Element-wise exponentiation (arr1 raised to the power of arr1)

array([ 1,  4, 27])

In [87]:
arr = np.sort(arr)  # Sort the array in ascending order
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])